### ISSUE TITLE
[bug] Inability to generate Swagger Docs

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery#10143]
### Current Behavior

```
➜  meshery git:(master) make swagger-build
swagger generate spec -o ./server/helpers/swagger.yaml --scan-models
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x68 pc=0x102db1a00]

goroutine 1 [running]:
github.com/go-openapi/spec.(*Schema).Typed(...)
        /home/runner/go/pkg/mod/github.com/go-openapi/spec@v0.20.9/schema.go:291
github.com/go-swagger/go-swagger/codescan.(*responseBuilder).buildFromField(0x14000983be0, 0x14052fe2000, {0x103112418?, 0x14052fb6a40?}, {0x103118190, 0x1407d6ffe50}, 0x103039fe0?)
        /home/runner/work/go-swagger/go-swagger/codescan/responses.go:188 +0x4d0
github.com/go-swagger/go-swagger/codescan.(*responseBuilder).buildFromField(0x14000983be0, 0x14052fe2000, {0x1031124b8?, 0x14052fba4d0?}, {0x103118240, 0x1409d28f120}, 0x103111720?)
        /home/runner/work/go-swagger/go-swagger/codescan/responses.go:185 +0x468
github.com/go-swagger/go-swagger/codescan.(*responseBuilder).buildFromStruct(0x14052ae64f8?, 0x1409d17e700, 0x14052fe07e0, 0x1409c67dda0, 0x14000983928?)
        /home/runner/work/go-swagger/go-swagger/codescan/responses.go:339 +0x638
github.com/go-swagger/go-swagger/codescan.(*responseBuilder).buildFromType(0x14000983be0, {0x103112440?, 0x140502f2d20}, 0x1409c67dda0, 0x140009839e8?)
        /home/runner/work/go-swagger/go-swagger/codescan/responses.go:234 +0x170
github.com/go-swagger/go-swagger/codescan.(*responseBuilder).Build(0x14000983be0, 0x102dc0ff0?)
        /home/runner/work/go-swagger/go-swagger/codescan/responses.go:148 +0x1cc
github.com/go-swagger/go-swagger/codescan.(*specBuilder).buildRespones(0x1409c88bd60)
        /home/runner/work/go-swagger/go-swagger/codescan/spec.go:170 +0x8c
github.com/go-swagger/go-swagger/codescan.(*specBuilder).Build(0x1409c88bd60)
        /home/runner/work/go-swagger/go-swagger/codescan/spec.go:57 +0x38
github.com/go-swagger/go-swagger/codescan.Run(0x14001a05ca8)
        /home/runner/work/go-swagger/go-swagger/codescan/application.go:77 +0x50
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.(*SpecFile).Execute(0x140000b0370, {0x140003ded70?, 0x140000b0370?, 0xb?})
        /home/runner/work/go-swagger/go-swagger/cmd/swagger/commands/generate/spec_go111.go:57 +0x150
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0x1400019f3b0, {0x140000301f0, 0x5, 0x5})
        /home/runner/go/pkg/mod/github.com/jessevdk/go-flags@v1.5.0/parser.go:335 +0x738
github.com/jessevdk/go-flags.(*Parser).Parse(...)
        /home/runner/go/pkg/mod/github.com/jessevdk/go-flags@v1.5.0/parser.go:191
main.main()
        /home/runner/work/go-swagger/go-swagger/cmd/swagger/swagger.go:140 +0xa30
make: *** [swagger-build] Error 2

```

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by lekaf974** [comment]
His this issue is still on going since I am seeing a PR merge ?

**Comment by leecalcote** [comment]
@lekaf974 good question. To confirm, you'll want to try running `make swagger-build` and see what you get...

**Comment by lekaf974** [comment]
I am able to reproduce locally, going to see if I am able to fix it
