### ISSUE TITLE
[UI] Error Occurs When Reloading or Directly Accessing URLs with Configurations/Designs

### ISSUE THREAD

**Issue by Kevin222004** [meshery/meshery#11246]
### Current Behavior
After setting up the server locally or on a remote provider and running the UI, an error occurs when directly accessing http://localhost:3000/configuration/designs in the browser or on reloading. However, if we navigate to this page step by step through the UI, it loads correctly without any issues.

### Desired Behavior
page should load correctly 

### Screenshots/Logs
[Issue.webm](https://github.com/meshery/meshery/assets/97679350/1b4d0121-8fe1-450d-9e9a-fb4a72f0756d)

###### logs
```
$ make ui
cd ui; npm run dev; cd ..;

> meshery-ui@1.0.0 dev
> next lint --fix && node ui_dev_server.js

(node:51782) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
✔ No ESLint warnings or errors
(node:51796) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Defining routes from exportPathMap
info  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
info  - `compiler` options in `next.config.js` will be ignored while using Babel https://nextjs.org/docs/messages/ignored-compiler-options
event - compiled client and server successfully in 6.4s (9055 modules)
> Ready on http://localhost:3000
wait  - compiling / (client and server)...
event - compiled client and server successfully in 2.3s (9535 modules)
(node:51796) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
Url '/configuration/designs' defines a query parameter '__nextDefaultLocale' that is missing in exportPathMap
wait  - compiling /configuration/designs (client and server)...
event - compiled client and server successfully in 7.7s (20909 modules)
error - ReferenceError: document is not defined
    at /home/kevin/Desktop/Meshery/meshery/ui/node_modules/codemirror/lib/codemirror.js:88:3
    at /home/kevin/Desktop/Meshery/meshery/ui/node_modules/codemirror/lib/codemirror.js:11:83
    at Object.<anonymous> (/home/kevin/Desktop/Meshery/meshery/ui/node_modules/codemirror/lib/codemirror.js:14:2)
    at Module._compile (node:internal/modules/cjs/loader:1460:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1544:10)
    at Module.load (node:internal/modules/cjs/loader:1275:32)
    at Module._load (node:internal/modules/cjs/loader:1091:12)
    at wrapModuleLoad (node:internal/modules/cjs/loader:212:19)
    at Module.require (node:internal/modules/cjs/loader:1297:12)
    at require (node:internal/modules/helpers:123:16) {
  page: '/configuration/designs'
}
wait  - compiling /_error (client and server)...

```

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by SSPlusUltra** [comment]
@Kevin222004   i couldn't repro this error. Can you make sure if it still exists? Thanks.

**Comment by Kevin222004** [comment]
@SSPlusUltra I have update my branch and rebuild all servers, I still have this issue.
