### ISSUE TITLE
[mesheryctl] `mesh validate` produces segfault

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#11304]
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

### Current Behavior
```
$ ➜  meshery git:(master) mesheryctl mesh validate
Unable to create a response from requestGet "http://localhost:31710/api/system/sync": dial tcp [::1]:31710: connect: connection refused
Unable to create a response from requestGet "http://localhost:31710/api/system/sync": dial tcp [::1]:31710: connect: connection refused
Verifying prerequisites...
Unable to create a response from requestGet "http://localhost:31710/api/system/sync": dial tcp [::1]:31710: connect: connection refused
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xef67735]

goroutine 1 [running]:
github.com/layer5io/meshery/mesheryctl/internal/cli/root/mesh.init.func6(0xc000561600?, {0x118fc9a0?, 0x0?, 0x0?})
	github.com/layer5io/meshery/mesheryctl/internal/cli/root/mesh/validate.go:72 +0x95
github.com/spf13/cobra.(*Command).execute(0x116d5680, {0x118fc9a0, 0x0, 0x0})
	github.com/spf13/cobra@v1.8.0/command.go:968 +0xa44
github.com/spf13/cobra.(*Command).ExecuteC(0x116d2b60)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/layer5io/meshery/mesheryctl/internal/cli/root.Execute()
	github.com/layer5io/meshery/mesheryctl/internal/cli/root/root.go:85 +0x45
main.main()
	github.com/layer5io/meshery/mesheryctl/cmd/mesheryctl/main.go:26 +0x13
```

### Environment

- Host OS: Mac 
- Meshery Server Version: not present
- Meshery Client Version: stable-v0.7.77
- Platform: not present

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- 📺 [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- ⌨️ [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- ⌨️ [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment]
Thanks much for jumping in, @Aijeyomah!

**Comment by Aijeyomah** [comment]
@leecalcote I recently experienced this exact issue while testing Meshery on Kubernetes after switching my laptop and reinstalling Kubernetes and Meshery. Below are the details of the problem and the solution I implemented:

Note: my port is `32108` instead of the `31710` from the issue description
### Problem Summary
**Issue:**
Meshery on Kubernetes is not accessible through the expected URL (`http://localhost:32108`). The services are not receiving external IPs, causing accessibility issues.

**Service Status:**
```sh
kubectl get svc -n meshery
```
```
NAME               TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                                                     AGE
meshery            LoadBalancer   10.107.5.122    <pending>     9081:32108/TCP                                                                              7m19s
meshery-broker     LoadBalancer   10.98.82.54     <pending>     4222:31840/TCP,6222:30900/TCP,8222:31663/TCP,7777:30149/TCP,7422:32696/TCP,7522:30570/TCP   6m33s
meshery-operator   ClusterIP      10.109.207.14   <none>        10000/TCP                                                                                   7m18s
```
The `meshery` and `meshery-broker` services have their `EXTERNAL-IP` in a `<pending>` state.

**Possible Causes:**
1. Kubernetes provider might not support LoadBalancer services.
2. Misconfiguration in the cluster setup or lack of necessary permissions for LoadBalancer provisioning.
3. Network policies or firewall rules might be blocking the access.

### Temporary Solution
Since I am using Minikube, I used port-forwarding as an alternative (NodePort can also be used).

**Steps:**
1. Set up port-forwarding:
   ```sh
   kubectl port-forward -n meshery svc/meshery 32108:9081
   ```
2. Access Meshery at:
   ```
   http://localhost:32108
   ```
3. Verified accessibility:
   - `http://localhost:32108/api/system/sync` became accessible.
   - Ran the validation command successfully:
     ```sh
     mesheryctl mesh validate istio --adapter meshery-istio --spec smi
     ```

The validation was successful, and other commands ran smoothly.

### Next Steps
We can verify if other team members are experiencing the same issue before I start Investigating the root cause of the LoadBalancer IPs being in the `<pending>` state and ensure that the Kubernetes setup supports LoadBalancer services.

**Comment by Fireentity** [comment]
Hello, I would like to work on solving this issue. I have my local environment set up and working correctly
