### ISSUE TITLE
[UI] Meshery UI Node Compatibility with v21

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#11474]
### Current Behavior

Meshery UI is incompatible with Node 21.

```
$ make ui-build

cd ui; npm run lint:fix && npm run build && npm run export; cd ..

> meshery-ui@1.0.0 lint:fix
> next lint --fix

(node:34653) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
✔ No ESLint warnings or errors

> meshery-ui@1.0.0 build
> npm run clean && cross-env next build


> meshery-ui@1.0.0 clean
> rm -rf .next,out

(node:34725) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info  - Linting and checking validity of types
info  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
info  - `compiler` options in `next.config.js` will be ignored while using Babel https://nextjs.org/docs/messages/ignored-compiler-options
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data .(node:34860) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info  - Collecting page data ..(node:34859) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info  - Collecting page data .(node:34861) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:34864) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:34863) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:34865) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:34862) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info  - Collecting page data ..ReferenceError: document is not defined
    at /Users/lee/code/meshery/ui/node_modules/codemirror/lib/codemirror.js:88:3
    at /Users/lee/code/meshery/ui/node_modules/codemirror/lib/codemirror.js:11:83
    at Object.<anonymous> (/Users/lee/code/meshery/ui/node_modules/codemirror/lib/codemirror.js:14:2)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/lee/code/meshery/ui/node_modules/react-codemirror2/index.js:70:8)

> Build error occurred
Error: Failed to collect page data for /configuration/filters
    at /Users/lee/code/meshery/ui/node_modules/next/dist/build/utils.js:916:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
```

### Environment

- Host OS: Mac M1
- Node Version: v21.6.2
- NPM Version: 10.2.4

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Aviral0702** [comment]
I would like to address this issue.

**Comment by rohitsrma** [comment]
Hii @leecalcote, I've tried reproducing this issue, but everything worked fine for me. Although I got similar deprecation warnings, the export was ultimately successful. Is there anything I'm missing?

```
> meshery-ui@1.0.0 lint:fix
> next lint --fix

(node:11924) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
✔ No ESLint warnings or errors

> meshery-ui@1.0.0 build
> npm run clean && cross-env next build


> meshery-ui@1.0.0 clean
> rm -rf .next,out

(node:12872) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info  - Linting and checking validity of types
info  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
info  - `compiler` options in `next.config.js` will be ignored while using Babel https://nextjs.org/docs/messages/ignored-compiler-options
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
info  - Creating an optimized production build ..
<--- Last few GCs --->

[12872:0x66c5ec0]   529414 ms: Mark-Compact (reduce) 1471.0 (1502.2) -> 1470.6 (1502.4) MB, 1156.31 / 0.00 ms  (average mu = 0.261, current mu = 0.002) allocation failure; scavenge might not succeed

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)


> provider-ui@1.0.0 export
> next export

 ⚠ "next export" is deprecated in favor of "output: export" in next.config.js https://nextjs.org/docs/advanced-features/static-html-export
   using build directory: /mnt/c/Users/boriw/OneDrive/Desktop/Meshery/meshery/provider-ui/.next
   Copying "static build" directory
 ⚠ Statically exporting a Next.js application via `next export` disables API routes and middleware.
This command is meant for static-only hosts, and is not necessary to make your application static.
Pages in your application without server-side data dependencies will be automatically statically exported by `next build`, including pages powered by `getStaticProps`.
Learn more: https://nextjs.org/docs/messages/api-routes-static-export
   Copying "public" directory
   Launching 3 workers
 ✓ Exporting (4/4)
Export successful. Files written to /mnt/c/Users/rohit/OneDrive/Desktop/Meshery/meshery/provider-ui/out
```

**Host OS - Windows 11**
**Node Version - v21.7.3**
**NPM Version - 10.5.0**

**Comment by leecalcote** [comment]
Thanks for confirming this, @rohitsrma. It seems like the issue might be more specific to Node 21+ on ARM.
