### ISSUE TITLE
[Server] Runtime Panic with NATS builtin encoder

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#12522]
### Current Behavior
Locally running Meshery Server crashes with:

```
created by github.com/99designs/gqlgen/graphql/handler/transport.(*wsConnection).subscribe in goroutine 9828
	/root/go/pkg/mod/github.com/99designs/gqlgen@v0.17.45/graphql/handler/transport/websocket.go:416 +0x58a
```

### Screenshots/Logs
See full server logs in 
[server-log.txt](https://github.com/user-attachments/files/17579410/server-log.txt)

````
...
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fbc2b5e04dc]

goroutine 9960 [running]:
runtime.throw({0x4fb1fae?, 0xc0014e0120?})
	/usr/local/go/src/runtime/panic.go:1077 +0x5c fp=0xc00138dd90 sp=0xc00138dd60 pc=0x18d805c
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:845 +0x3e9 fp=0xc00138ddf0 sp=0xc00138dd90 pc=0x18f0609
runtime: g 9960: unexpected return pc for runtime.sigpanic called from 0x7fbc2b5e04dc
stack: frame={sp:0xc00138dd90, fp:0xc00138ddf0} stack=[0xc00138d000,0xc00138e000)
0x000000c00138dc90:  0x000000c001632690  0x000000c0016326c0
0x000000c00138dca0:  0x000000c00138dd10  0x0000000001c3105e <encoding/json.(*decodeState).value+0x000000000000003e>
0x000000c00138dcb0:  0x000000c0014e0120  0x0000000004685440
0x000000c00138dcc0:  0x000000c0022fe040  0x000000c00138dd08
0x000000c00138dcd0:  0x000000c00138dd10  0x0000000001c30e1d <encoding/json.(*decodeState).scanWhile+0x000000000000007d>
0x000000c00138dce0:  0x000000c0014e0148  0x00000000018b8e76 <runtime.gcTrigger.test+0x00000000000000b6>
0x000000c00138dcf0:  0x0000000000000000  0x000000000000b8a5
0x000000c00138dd00:  0x000000c0014e0148  0x000000000190e912 <runtime.systemstack+0x0000000000000032>
0x000000c00138dd10:  0x000000c00138dd50  0x00000000018d8365 <runtime.fatalthrow+0x0000000000000065>
0x000000c00138dd20:  0x000000c00138dd30  0x000000c0013311e0
0x000000c00138dd30:  0x00000000018d83a0 <runtime.fatalthrow.func1+0x0000000000000000>  0x000000c0013311e0
0x000000c00138dd40:  0x00000000018d805c <runtime.throw+0x000000000000005c>  0x000000c00138dd60
0x000000c00138dd50:  0x000000c00138dd80  0x00000000018d805c <runtime.throw+0x000000000000005c>
0x000000c00138dd60:  0x000000c00138dd68  0x00000000018d8080 <runtime.throw.func1+0x0000000000000000>
0x000000c00138dd70:  0x0000000004fb1fae  0x000000000000002a
0x000000c00138dd80:  0x000000c00138dde0  0x00000000018f0609 <runtime.sigpanic+0x00000000000003e9>
0x000000c00138dd90: <0x0000000004fb1fae  0x000000c0014e0120
0x000000c00138dda0:  0x0000000004685440  0x000000c0022fe040
0x000000c00138ddb0:  0x000000c00138dde0  0x00007fbc2b5dfb25
0x000000c00138ddc0:  0x000000c0013311e0  0x00000000038d4ab2 <github.com/nats-io/nats.go/encoders/builtin.(*JsonEncoder).Decode+0x0000000000000192>
0x000000c00138ddd0:  0x0000000000000001  0x000000c0035a4420
0x000000c00138dde0:  0x000000c00138df00  0x00007fbc2b5e04dc
0x000000c00138ddf0: >0x000000c00138df98  0x0000000000000002
0x000000c00138de00:  0x000000c00e662420  0x000000c00138df5c
0x000000c00138de10:  0x0000000000000002  0x000000c00e662450
0x000000c00138de20:  0x00000000055c2288  0x0000000000000000
0x000000c00138de30:  0x0000000000000002  0x000000c0035a4420
0x000000c00138de40:  0x00000000049ab820  0x000000c0002e4210
0x000000c00138de50:  0x000000c000a92000  0x0000000000000000
0x000000c00138de60:  0x0000000000000000  0x0000000000000001
0x000000c00138de70:  0x0000000000000002  0x0000000001000100
0x000000c00138de80:  0x0000000000000000  0x000000c000c880a0
0x000000c00138de90:  0x000000c00138df5c  0x000000c0013311e0
0x000000c00138dea0:  0x000000c003e27eb8  0x000000c0035a4420
0x000000c00138deb0:  0x000000c00018ede0  0x000000c00018ede0
0x000000c00138dec0:  0x00000000019470c4 <context.(*valueCtx).Done+0x0000000000000024>  0x000000c003e27f00
0x000000c00138ded0:  0x000000c00138dee8  0x00000000019470c4 <context.(*valueCtx).Done+0x0000000000000024>
0x000000c00138dee0:  0x00007fbc00000004  0x000000c00138df00

goroutine 1 [chan receive, 25 minutes]:
runtime.gopark(0xc0021a6f60?, 0x18ab2fd?, 0x0?, 0x60?, 0x20?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc000f26ef8 sp=0xc000f26ed8 pc=0x18dbbae
runtime.chanrecv(0xc001d4ef00, 0x0, 0x1)
	/usr/local/go/src/runtime/chan.go:583 +0x3cd fp=0xc000f26f70 sp=0xc000f26ef8 pc=0x18a432d
runtime.chanrecv1(0xc001d4ef00?, 0xc0021a75a0?)
	/usr/local/go/src/runtime/chan.go:442 +0x12 fp=0xc000f26f98 sp=0xc000f26f70 pc=0x18a3f32
main.main()
	/root/meshery/server/cmd/main.go:372 +0x377d fp=0xc000f27f40 sp=0xc000f26f98 pc=0x4432edd
runtime.main()
	/usr/local/go/src/runtime/proc.go:267 +0x2bb fp=0xc000f27fe0 sp=0xc000f27f40 pc=0x18db73b
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000f27fe8 sp=0xc000f27fe0 pc=0x19108a1
...
```

### Environment

- **Host OS:**  Linux Ubuntu
- **Platform:** Local
- **Meshery Server Version:** stable-v0.7.129


<!-- Optional 
### To Reproduce
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
-->

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Eyepatch5263** [comment]
If this issue is still open, can you assign it to me?

**Comment by Omkar-Ugal** [comment]
I tried reproducing this locally with the current Meshery server and NATS setup, but I wasn’t able to trigger the runtime panic mentioned in the logs. I tested publishing different payloads (including malformed and frequent messages) and monitored the server logs, but everything seemed to be handled without crashes.

It’s possible this was resolved through dependency updates since the original report. Could someone confirm if this is still reproducible on the latest version? If not, we might consider closing this issue.

Happy to help investigate further if there are specific repro steps. Thanks!

**Comment by lucasbryant1222-png** [comment]
Any fix

**Comment by Omkar-Ugal** [comment]
> Any fix
> […](#)

I wasn’t able to reproduce the panic on the latest Meshery version during my local testing. It’s possible that this issue may have been resolved through dependency updates since the original report.

If you're still encountering the crash, could you please share:

Meshery Server version

Host OS and environment (local / Kubernetes / Docker Desktop)

Steps to reproduce the issue

Relevant server logs or stack trace

**Comment by jjs7233** [comment]
Hi, I investigated this issue by searching the current codebase.

Searches for `nats encoder`, `JsonEncoder`, and `nats builtin encoder` 
all return 0 files. The NATS builtin encoder dependency has been fully 
removed from the repository, which resolves this panic at the root.

I believe this issue can be closed. Could a maintainer confirm?
