### ISSUE TITLE
[meshery-server] panic while uploading SMI results to remote provider

### ISSUE THREAD

**Issue by DelusionalOptimist** [meshery/meshery#4079]
#### Current Behavior
If remote provider token expires during the duration of SMI conformance test, Meshery server would panic when trying to refresh it. This might take some patience to reproduce.

#### Expected Behavior
Don't panic and refresh the token.

#### Screenshots/Logs
* Performing SMI conformance tests. Token expires and server tries to get it refreshed but panics and exits:
```
time="2021-09-02T22:21:15Z" level=info msg="attempting to publish results to remote provider"
time="2021-09-02T22:21:17Z" level=warning msg="trying after refresh"
time="2021-09-02T22:21:17Z" level=info msg="token refresh successful"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x25ff6d6]

goroutine 23089 [running]:
github.com/layer5io/meshery/models.(*RemoteProvider).PublishSmiResults(0xc000716a80, 0xc000ba02d0, 0x0, 0x0, 0x0, 0x0)
        /github.com/meshery/meshery/models/remote_provider.go:661 +0x836
github.com/layer5io/meshery/handlers.listenForAdapterEvents(0x32a1108, 0xc0008da330, 0xc0010dfe90, 0xc0026553e0, 0xc00041d1f0, 0x32d6cc0, 0xc000716a80)
        /github.com/meshery/meshery/handlers/events_streamer.go:189 +0x40d
github.com/layer5io/meshery/handlers.(*Handler).EventStreamHandler.func1.1(0xc000174d00, 0xc0026553e0, 0xc00041d1f0, 0x32d6cc0, 0xc000716a80, 0xc0010dfe90)
        /github.com/meshery/meshery/handlers/events_streamer.go:70 +0x79
created by github.com/layer5io/meshery/handlers.(*Handler).EventStreamHandler.func1
        /github.com/meshery/meshery/handlers/events_streamer.go:69 +0xfa
```
* On restarting the same container, these are the logs. The message `Token is invalid` proves that the token was not refreshed:
```
time="2021-09-02T22:22:21Z" level=info msg="Registered Meshery local Capabilities"
time="2021-09-02T22:22:21Z" level=info msg="Meshery server current channel: stable"
time="2021-09-02T22:22:21Z" level=info msg="Using '/home/appuser/.meshery/config' to store user data"
time="2021-09-02T22:22:21Z" level=info msg="Using '/home/appuser/.kube' as the folder to look for kubeconfig file"
time="2021-09-02T22:22:21Z" level=info msg="Log level: info"
taskq: 2021/09/02 22:22:21 consumer_config.go:249: taskq: system does not have enough free resources
time="2021-09-02T22:22:23Z" level=info msg="Starting Server listening on :9081"
time="2021-09-02T22:22:30Z" level=info msg="Token validation error : Token is invalid, it has expired"
time="2021-09-02T22:22:41Z" level=info msg="Token validation error : Token is invalid, it has expired"
time="2021-09-02T22:22:53Z" level=info msg="Token validation error : Token is invalid, it has expired"
time="2021-09-02T22:23:07Z" level=info msg="Token validation error : Token is invalid, it has expired"
time="2021-09-02T22:23:16Z" level=info msg="Token validation error : Token is invalid, it has expired"
```

#### Environment

- **Host OS:** Linux
- **Platform:** Docker
- **Meshery Server Version:** stable-v0.5.52
- **Meshery Client Version:** stable-v0.5.52

#### To Reproduce
1. Login with the remote provider.
2. Try to install a service mesh and run SMI conformance tests.
3. Keep running conformance tests (or any other activity which uses the provider token and coincides with its expiry time) so that token can expire and refresh can take place.
4. See panic.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by DelusionalOptimist** [comment]
Closing this since https://github.com/meshery/meshery/pull/4109 addressed the panic while refreshing tokens.
