### ISSUE TITLE
[UI] Meshery deployed on Kind Kubernetes doesn't work 

### ISSUE THREAD

**Issue by gyohuangxin** [meshery/meshery#4201]
#### Current Behavior

There are some error msgs from Meshery UI:
![image](https://user-images.githubusercontent.com/42127654/133818333-9e9f23d5-54e4-4d05-8cae-cd4f590e9321.png)

And there are many error msgs from Meshery pod's log:
```
time="2021-09-17T23:52:25Z" level=info msg="Registered Meshery local Capabilities"
time="2021-09-17T23:52:25Z" level=info msg="Meshery server current channel: stable"
time="2021-09-17T23:52:25Z" level=info msg="Using '/home/appuser/.meshery/config' to store user data"
time="2021-09-17T23:52:25Z" level=info msg="Using '/home/appuser/.kube' as the folder to look for kubeconfig file"
time="2021-09-17T23:52:25Z" level=info msg="Log level: info"
time="2021-09-17T23:52:56Z" level=error msg="[Initialize Provider]: Failed to get capabilities Get \"https://meshery.layer5.io/v0.5.57/capabilities?os=meshery\": dial tcp 3.22.255.79:443: i/o timeout"
time="2021-09-17T23:52:56Z" level=info msg="Starting Server listening on :8080"
time="2021-09-17T23:55:30Z" level=warning msg="unable to find session for user with id: meshery."
time="2021-09-17T23:55:30Z" level=error app=meshery code=2033 probable-cause="The file does not exist in the location" severity=2 short-description="unable to open file: ./home/appuser/.kube/config" suggested-remediation="Make sure to upload the correct file"
time="2021-09-17T23:55:32Z" level=error msg="rpc error: code = Unimplemented desc = unknown method ComponentInfo for service meshes.MeshService" app=meshery code=2041 probable-cause="unable to retrieve the requested data" severity=2 short-description="Error getting operations for the mesh.Error getting service mesh name" suggested-remediation="Make sure adapter is reachable and running"
time="2021-09-17T23:55:33Z" level=error msg="rpc error: code = Unimplemented desc = unknown method ComponentInfo for service meshes.MeshService" app=meshery code=2041 probable-cause="unable to retrieve the requested data" severity=2 short-description="Error getting operations for the mesh.Error getting service mesh name" suggested-remediation="Make sure adapter is reachable and running"
time="2021-09-17T23:56:33Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-17T23:56:33Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-17T23:56:33Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-17T23:56:33Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-17T23:56:33Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-17T23:56:33Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-17T23:56:33Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-17T23:57:33Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-17T23:57:33Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-17T23:57:33Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-17T23:57:33Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-17T23:57:33Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-17T23:57:33Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-17T23:57:33Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-17T23:58:33Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-17T23:58:33Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-17T23:58:33Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-17T23:58:33Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-17T23:58:33Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-17T23:58:33Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-17T23:58:33Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-17T23:59:35Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-17T23:59:35Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-17T23:59:35Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-17T23:59:35Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-17T23:59:35Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-17T23:59:35Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-17T23:59:35Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-18T00:00:35Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-18T00:00:35Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-18T00:00:35Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-18T00:00:35Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-18T00:00:35Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-18T00:00:35Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-18T00:00:35Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-18T00:01:35Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-18T00:01:35Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-18T00:01:35Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-18T00:01:35Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-18T00:01:35Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-18T00:01:35Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-18T00:01:35Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-18T00:02:36Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-18T00:02:36Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-18T00:02:36Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-18T00:02:36Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-18T00:02:36Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-18T00:02:36Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-18T00:02:36Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-18T00:03:04Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-18T00:03:04Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-18T00:03:04Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-18T00:03:04Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-18T00:03:04Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-18T00:03:04Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-18T00:03:04Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-18T00:03:20Z" level=error msg="rpc error: code = Unimplemented desc = unknown method ComponentInfo for service meshes.MeshService" app=meshery code=2041 probable-cause="unable to retrieve the requested data" severity=2 short-description="Error getting operations for the mesh.Error getting service mesh name" suggested-remediation="Make sure adapter is reachable and running"
time="2021-09-18T00:03:20Z" level=error msg="rpc error: code = Unimplemented desc = unknown method ComponentInfo for service meshes.MeshService" app=meshery code=2041 probable-cause="unable to retrieve the requested data" severity=2 short-description="Error getting operations for the mesh.Error getting service mesh name" suggested-remediation="Make sure adapter is reachable and running"
```

#### Screenshots/Logs

All the Meshery service are running:
```
huangxin@huangxin:~/kind$ kc get all -n meshery
NAME                                        READY   STATUS    RESTARTS   AGE
pod/meshery-658df44c57-44qdh                1/1     Running   0          21m
pod/meshery-consul-dcdb77f96-c6qvq          1/1     Running   0          31m
pod/meshery-cpx-79fb9656bc-qnfnf            1/1     Running   0          31m
pod/meshery-istio-64c757bbc8-kt5zm          1/1     Running   0          31m
pod/meshery-kuma-6669cc5979-87f4h           1/1     Running   0          31m
pod/meshery-linkerd-5c8c7756db-5z7tc        1/1     Running   0          31m
pod/meshery-nginx-sm-5676f9f8dd-cv5qb       1/1     Running   0          31m
pod/meshery-nsm-78b44df4f6-klmmp            1/1     Running   0          31m
pod/meshery-octarine-bd4678b4b-bnqn8        1/1     Running   0          31m
pod/meshery-osm-7bb65bf558-s6p4p            1/1     Running   0          31m
pod/meshery-traefik-mesh-6778958fd4-2wwbc   1/1     Running   0          31m

NAME                           TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
service/meshery                LoadBalancer   10.96.119.144   <pending>     9081:31047/TCP   31m
service/meshery-consul         ClusterIP      10.96.18.141    <none>        10002/TCP        31m
service/meshery-cpx            ClusterIP      10.96.63.33     <none>        10008/TCP        31m
service/meshery-istio          ClusterIP      10.96.216.155   <none>        10000/TCP        31m
service/meshery-kuma           ClusterIP      10.96.71.255    <none>        10007/TCP        31m
service/meshery-linkerd        ClusterIP      10.96.163.140   <none>        10001/TCP        31m
service/meshery-nginx-sm       ClusterIP      10.96.99.235    <none>        10010/TCP        31m
service/meshery-nsm            ClusterIP      10.96.193.171   <none>        10004/TCP        31m
service/meshery-octarine       ClusterIP      10.96.105.42    <none>        10003/TCP        31m
service/meshery-osm            ClusterIP      10.96.101.140   <none>        10009/TCP        31m
service/meshery-traefik-mesh   ClusterIP      10.96.201.255   <none>        10006/TCP        31m

NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/meshery                1/1     1            1           31m
deployment.apps/meshery-consul         1/1     1            1           31m
deployment.apps/meshery-cpx            1/1     1            1           31m
deployment.apps/meshery-istio          1/1     1            1           31m
deployment.apps/meshery-kuma           1/1     1            1           31m
deployment.apps/meshery-linkerd        1/1     1            1           31m
deployment.apps/meshery-nginx-sm       1/1     1            1           31m
deployment.apps/meshery-nsm            1/1     1            1           31m
deployment.apps/meshery-octarine       1/1     1            1           31m
deployment.apps/meshery-osm            1/1     1            1           31m
deployment.apps/meshery-traefik-mesh   1/1     1            1           31m

NAME                                              DESIRED   CURRENT   READY   AGE
replicaset.apps/meshery-658df44c57                1         1         1       31m
replicaset.apps/meshery-consul-dcdb77f96          1         1         1       31m
replicaset.apps/meshery-cpx-79fb9656bc            1         1         1       31m
replicaset.apps/meshery-istio-64c757bbc8          1         1         1       31m
replicaset.apps/meshery-kuma-6669cc5979           1         1         1       31m
replicaset.apps/meshery-linkerd-5c8c7756db        1         1         1       31m
replicaset.apps/meshery-nginx-sm-5676f9f8dd       1         1         1       31m
replicaset.apps/meshery-nsm-78b44df4f6            1         1         1       31m
replicaset.apps/meshery-octarine-bd4678b4b        1         1         1       31m
replicaset.apps/meshery-osm-7bb65bf558            1         1         1       31m
replicaset.apps/meshery-traefik-mesh-6778958fd4   1         1         1       31m
```
And I use nginx ingress controller to expose Meshery serivce.
The ingress yaml file:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: meshery-ingress
  namespace: meshery
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: meshery
          servicePort: 9081
```

#### Environment

- **Host OS:** Linux (Ubuntu 20.04)
- **Platform:** Kubernetes (Kind)
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by gyohuangxin** [comment]
More Info you can refer to, below is all the steps I setup Meshery with Kind.

### Create multi-node Kubernetes test cluster with Kind

Prepare kind configuration yaml

`$ cat kind.yaml`

```go
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
- role: worker
```

To tell KIND to use this configuration you can use the “–config” option:

`$ kind create cluster --name=meshery-test --config=./kind.yml`

Install a Ingress Controller for Kubernetes, such as Nginx Controller

`kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml`

### Install Meshery

To install Meshery on your cluster, clone the Meshery repo:

```
git clone [https://github.com/meshery/meshery.git;](https://github.com/meshery/meshery.git;)
cd meshery
```

Create a namespace as a new logical space to host Meshery and its components:

```
kubectl create ns meshery
```

All the needed deployment yamls for deploying Meshery are included in the install/deployment_yamls/k8s folder inside the cloned Meshery folder. To deploy the yamls on the cluster please run the following command:

```
kubectl -n meshery apply -f install/deployment_yamls/k8s
```

Configure the ingress to expose Meshery:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: meshery-ingress
  namespace: meshery
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
       # Please kindly check your service name and service port to confirm the Ingress can work well
          serviceName: meshery
          servicePort: 9081
```

**Comment by leecalcote** [comment]
@gyohuangxin, thank you for reporting this!

**Comment by leecalcote** [comment]
@gyohuangxin The installation method of directly deploying Meshery via Kubernetes manifests is a method that the project is trying to move away from. We're in need of eventually removing the direct manifest method that is published here - https://meshery.io/#getting-started

<img width="1109" alt="Screen Shot 2021-09-17 at 5 08 03 PM" src="https://user-images.githubusercontent.com/7570704/133858807-7c3266ed-a53f-4471-b3f2-7fb4aa89ae32.png">

Meshery needs to gracefully handle the scenario in which no Meshery Operator is present on the connected Kubernetes cluster (it is missing in your environment output above). The manifests listed in the `/install` folder in the repo are missing manifests for [Meshery Operator](https://docs.meshery.io/concepts/architecture/operator) (and its two custom controllers). @panyuenlau made a recent fix to the Helm charts. 

Between using the Helm charts or the `mesheryctl` approach to installation, you should find Meshery to be in working condition in the v0.5.58 release. Thank you for the excellent issue write-up, @gyohuangxin. Let's get this fixed promptly. 

You're most welcome to join the community Slack, if you haven't already - http://slack.meshery.io.

**Comment by gyohuangxin** [comment]
@leecalcote Thanks, your answer is very helpful. And I found the PR to fix Helm charts issue has been merged, so I will try to use Helm.

**Comment by gyohuangxin** [comment]
@leecalcote Hi, I can install Meshery with helm methods. However there are still some issues when I try to install service mesh on my cluster. 
The steps to reproduce:
1. There are some errors in meshery-xxxx pod:
```
$  kubectl logs meshery-58f5449cc-x5k5k -n meshery
time="2021-09-22T14:43:32Z" level=info msg="Initializing MeshSync subscription" app=meshery
time="2021-09-22T14:43:32Z" level=info msg="Operator subscription started" app=meshery
time="2021-09-22T14:43:32Z" level=info msg="Initializing DataPlane subscription" app=meshery
time="2021-09-22T14:43:32Z" level=info msg="Initializing ControlPlane subscription" app=meshery
time="2021-09-22T14:43:37Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-22T14:43:37Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-22T14:43:37Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-22T14:43:37Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-22T14:43:37Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-22T14:43:37Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-22T14:43:37Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer
time="2021-09-22T14:43:37Z" level=info msg="DataPlane subscription stopped" app=meshery
time="2021-09-22T14:43:37Z" level=info msg="ControlPlane subscription stopped" app=meshery
time="2021-09-22T14:43:37Z" level=info msg="Operator subscription flushed" app=meshery
time="2021-09-22T14:43:37Z" level=info msg="Operator subscription flushed" app=meshery
time="2021-09-22T14:44:27Z" level=error msg="Unable to create a mesh client.Unable to ping the mesh adapter" app=meshery code=2039 probable-cause="Adapter could not be pinged" severity=2 short-description="Error creating a mesh client.Error pinging the mesh adapter" suggested-remediation="Unable to connect to the Mesh adapter using the given config, please try again"
time="2021-09-22T14:44:27Z" level=info msg="Initializing MeshSync subscription" app=meshery
time="2021-09-22T14:44:27Z" level=info msg="Operator subscription started" app=meshery
time="2021-09-22T14:44:27Z" level=info msg="Initializing ControlPlane subscription" app=meshery
time="2021-09-22T14:44:27Z" level=info msg="Initializing DataPlane subscription" app=meshery
time="2021-09-22T14:44:27Z" level=error msg="rpc error: code = Unimplemented desc = unknown method ComponentInfo for service meshes.MeshService" app=meshery code=2041 probable-cause="unable to retrieve the requested data" severity=2 short-description="Error getting operations for the mesh.Error getting service mesh name" suggested-remediation="Make sure adapter is reachable and running"
time="2021-09-22T14:44:29Z" level=info msg="Operator subscription flushed" app=meshery
time="2021-09-22T14:44:29Z" level=info msg="ControlPlane subscription stopped" app=meshery
time="2021-09-22T14:44:29Z" level=info msg="DataPlane subscription stopped" app=meshery
time="2021-09-22T14:44:29Z" level=info msg="Initializing MeshSync subscription" app=meshery
time="2021-09-22T14:44:29Z" level=info msg="Addons subscription started" app=meshery
time="2021-09-22T14:44:29Z" level=info msg="Operator subscription started" app=meshery
time="2021-09-22T14:44:35Z" level=error msg="rpc error: code = Unavailable desc = error reading from server: EOF" file=events_streamer
time="2021-09-22T14:44:35Z" level=error msg="rpc error: code = Unavailable desc = error reading from server: EOF" file=events_streamer
time="2021-09-22T14:44:57Z" level=error msg="Get \"https://api.github.com/repos/meshery/meshery/tags\": dial tcp 13.250.168.23:443: i/o timeout" app=meshery code=2138 probable-cause= severity=2 short-description="failed to compare latest and current version of Meshery" suggested-remediation=
time="2021-09-22T14:45:25Z" level=error msg="rpc error: code = Canceled desc = context canceled" file=events_streamer```
```

2. Try to install istio service mesh from GUI
![image](https://user-images.githubusercontent.com/42127654/134303883-4eff99f0-144b-4d8f-a082-82d1c35060e4.png)

3. The meshery-istio-xxxx pod will be killed and restarted with error message:
```
$ kubectl logs meshery-istio-db9b99584-rgq5z -n meshery -f
time="2021-09-22T15:48:17Z" level=info msg="Adaptor Listening at port: 10000" app=istio-adaptor
time="2021-09-22T15:48:19Z" level=info msg="Creating instance" app=istio-adaptor
time="2021-09-22T15:48:21Z" level=info msg="Creating instance" app=istio-adaptor
time="2021-09-22T15:48:25Z" level=info msg="Creating instance" app=istio-adaptor
time="2021-09-22T15:48:29Z" level=info msg="Creating instance" app=istio-adaptor
time="2021-09-22T15:49:25Z" level=info msg="Creating instance" app=istio-adaptor
time="2021-09-22T15:49:26Z" level=info msg="Creating instance" app=istio-adaptor
time="2021-09-22T15:49:26Z" level=info msg="Applying operation istio" app=istio-adaptor
panic: runtime error: index out of range [0] with length 0

goroutine 918 [running]:
github.com/meshery/meshery-istio/istio.(*Istio).ApplyOperation.func1(0xc0006184f0, 0xc0028bd6a8, 0x5, 0xc0028bd6b0, 0xc, 0xc0028bd6c0, 0x7, 0x0, 0x0, 0x0, ...)
        /build/istio/istio.go:51 +0x49a
created by github.com/meshery/meshery-istio/istio.(*Istio).ApplyOperation
        /build/istio/istio.go:50 +0x9ba
```

Can you provide some advices? Thank you.
