### ISSUE TITLE
[Meshery Server] Patterns endpoint failure

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5070]
#### Current Behavior
On load of http://localhost:9081/configuration/patterns, users see:

<img width="438" alt="Screen Shot 2022-02-14 at 4 38 49 PM" src="https://user-images.githubusercontent.com/7570704/153958621-c53dce4d-24a5-4dfe-8d1a-207c0651389d.png">

#### Screenshots/Logs
```
INFO[6780] retrieved user: {lcalcote   http://pbs.twimg.com/profile_images/880205475643441152/V_vhfnzb_normal.jpg}
INFO[6780] attempting to fetch current kubernetes contexts from cloud
DEBU[6780] constructed kubernetes contexts url: https://meshery.layer5.io/user/contexts/6a657292-189b-4f84-8bfb-e4bec13400cd/current
INFO[6780] kubernetes context successfully retrieved from remote provider
16:38:37 http: panic serving [::1]:63744: interface conversion: interface {} is nil, not string
goroutine 36583 [running]:
net/http.(*conn).serve.func1(0xc0002b86e0)
	/Users/lee/sdk/go1.16.4/src/net/http/server.go:1824 +0x153
panic(0x6463140, 0xc0017edbc0)
	/Users/lee/sdk/go1.16.4/src/runtime/panic.go:971 +0x499
github.com/layer5io/meshery/handlers.(*Handler).GetMesheryPatternsHandler(0xc0010e1380, 0x6bf1b20, 0xc000c04700, 0xc0009fc800, 0xc001b330e0, 0xc0000b1bd0, 0x6c3ab58, 0xc000102d80)
	/Users/lee/code/meshery/handlers/meshery_pattern_handler.go:267 +0xa65
github.com/layer5io/meshery/handlers.(*Handler).PatternFileRequestHandler(0xc0010e1380, 0x6bf1b20, 0xc000c04700, 0xc0009fc800, 0xc001b330e0, 0xc0000b1bd0, 0x6c3ab58, 0xc000102d80)
	/Users/lee/code/meshery/handlers/meshery_pattern_handler.go:37 +0x10e
github.com/layer5io/meshery/handlers.(*Handler).SessionInjectorMiddleware.func1(0x6bf1b20, 0xc000c04700, 0xc0009fc100)
	/Users/lee/code/meshery/handlers/middlewares.go:167 +0x8d9
net/http.HandlerFunc.ServeHTTP(0xc00064fbc0, 0x6bf1b20, 0xc000c04700, 0xc0009fc100)
	/Users/lee/sdk/go1.16.4/src/net/http/server.go:2069 +0x44
github.com/layer5io/meshery/handlers.(*Handler).AuthMiddleware.func1(0x6bf1b20, 0xc000c04700, 0xc0009fc100)
	/Users/lee/code/meshery/handlers/middlewares.go:65 +0x129
net/http.HandlerFunc.ServeHTTP(0xc001410080, 0x6bf1b20, 0xc000c04700, 0xc0009fc100)
	/Users/lee/sdk/go1.16.4/src/net/http/server.go:2069 +0x44
github.com/layer5io/meshery/handlers.(*Handler).ProviderMiddleware.func1(0x6bf1b20, 0xc000c04700, 0xc0023bdf00)
	/Users/lee/code/meshery/handlers/middlewares.go:33 +0x1e7
net/http.HandlerFunc.ServeHTTP(0xc0014100a0, 0x6bf1b20, 0xc000c04700, 0xc0023bdf00)
	/Users/lee/sdk/go1.16.4/src/net/http/server.go:2069 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000850cc0, 0x6bf1b20, 0xc000c04700, 0xc002f1af00)
	/Users/lee/code/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
net/http.serverHandler.ServeHTTP(0xc000c04460, 0x6bf1b20, 0xc000c04700, 0xc002f1af00)
	/Users/lee/sdk/go1.16.4/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc0002b86e0, 0x6bf8de8, 0xc00452fac0)
	/Users/lee/sdk/go1.16.4/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/Users/lee/sdk/go1.16.4/src/net/http/server.go:3013 +0x39b
error in cleanupremove /Users/lee/.meshery/bin/test.yaml: no such file or directory
INFO[2022-02-14T16:38:41-06:00] Registration of k8s native components completed  app=meshery
INFO[2022-02-14T16:38:41-06:00] Registration of k8s native components completed  app=meshery
ERRO[6784] unexpected end of JSON input
````
#### Environment

- **Meshery Server Version:** edge

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by manav1403** [comment]
The following endpoints are failing as from the networking tab when loading Meshmap

- `Request URL: http://localhost:9081/api/pattern?page=&page_size=&search=&order=`
- `Request URL: http://localhost:9081/api/user/performance/profiles`

![image](https://user-images.githubusercontent.com/51405571/154083717-dd9fd7eb-a70f-4570-8fba-fb298ec06e3e.png)

**Comment by leecalcote** [comment]
@Revolyssup was this recently fixed?

**Comment by Revolyssup** [comment]
> @Revolyssup was this recently fixed?

yes its fixed.
