### ISSUE TITLE
[Server] Remote Kubernetes Connection: Failure in Operator Deployment

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#6587]
#### Current Behavior
Meshery Server crashes on click of toggle in Settings-->Environments page for a remote K8s cluster (in this case - AKS)

#### Screenshots/Logs
```
time="2022-11-29T18:46:14Z" level=info msg="attempting to fetch kubernetes contexts from cloud for context id: a3e3116fe0617a8a28a2d404e9c94c17"
time="2022-11-29T18:46:14Z" level=info msg="kubernetes context successfully retrieved from remote provider"
time="2022-11-29T18:46:24Z" level=info msg="registration of k8s native components completed for contextID: def27dd2c809c8a5e75a776353d01327" app=meshery
time="2022-11-29T18:49:05Z" level=info msg="attempting to fetch kubernetes contexts from cloud for Meshery instance: b198f2a4-73d2-4c76-b57d-07374b3eaa64"
time="2022-11-29T18:49:07Z" level=info msg="kubernetes contexts successfully retrieved from remote provider"
time="2022-11-29T18:49:07Z" level=info msg="Installing Operator" app=meshery
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x380ce0c]

goroutine 109007 [running]:
github.com/layer5io/meshery/server/internal/graphql/resolver.(*Resolver).changeOperatorStatus.func1(0x0, 0xc000b86f88?)
        /github.com/meshery/meshery/server/internal/graphql/resolver/operator.go:90 +0x12c
created by github.com/layer5io/meshery/server/internal/graphql/resolver.(*Resolver).changeOperatorStatus
        /github.com/meshery/meshery/server/internal/graphql/resolver/operator.go:84 +0x645
```

#### Environment

- **Host OS:** Mac
- **Platform:** Kubernetes
- **Meshery Server Version:** stable-v0.6.30-stable
- **Meshery Client Version:** stable-v0.6.30-stable

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by EleisonC** [comment]
Hey @leecalcote I would like to get my hands dirty with this task if still available

**Comment by abhishekkumarsahu1234567-rgb** [comment]
@leecalcote Hi, I’m interested in working on this issue. I’d like to take this up and contribute a fix. Please let me know if it’s available. Thank you!
