### ISSUE TITLE
[CI] ui-integration tests are unable to start (Error: error:0308010C:digital envelope routines::unsupported, ERR_OSSL_EVP_UNSUPPORTED)

### ISSUE THREAD

**Issue by MarioArriaga92** [meshery/meshery#6864]
#### Current Behavior
There's a recurrent issue during running meshery cypress integration tests ('ci-test-integration' npm script called by [our buld-ui-and-server.yml ci workflow](https://github.com/meshery/meshery/blob/master/.github/workflows/build-ui-and-server.yml#L119)) in which we get the following error (see [here](https://github.com/meshery/meshery/actions/runs/3835743870/jobs/6529301044) for example):
```
> meshery-ui@1.0.0 dev16
> eslint . --fix && node ui_dev_server.js

info  - Using webpack 4. Reason: custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports.__webpack_modules__.15660.module.exports (/home/runner/work/meshery/meshery/ui/node_modules/next/dist/compiled/webpack/bundle4.js:111680:62)
    at NormalModule._initBuildHash (/home/runner/work/meshery/meshery/ui/node_modules/next/dist/compiled/webpack/bundle4.js:85092:16)
    at handleParseError (/home/runner/work/meshery/meshery/ui/node_modules/next/dist/compiled/webpack/bundle4.js:85146:10)
    at /home/runner/work/meshery/meshery/ui/node_modules/next/dist/compiled/webpack/bundle4.js:851[78](https://github.com/meshery/meshery/actions/runs/3835743870/jobs/6529301044#step:5:79):5
    at /home/runner/work/meshery/meshery/ui/node_modules/next/dist/compiled/webpack/bundle4.js:[85](https://github.com/meshery/meshery/actions/runs/3835743870/jobs/6529301044#step:5:86)033:12
    at /home/runner/work/meshery/meshery/ui/node_modules/next/dist/compiled/webpack/bundle4.js:51096:3
    at iterateNormalLoaders (/home/runner/work/meshery/meshery/ui/node_modules/next/dist/compiled/webpack/bundle4.js:50937:10)
    at Array.<anonymous> (/home/runner/work/meshery/meshery/ui/node_modules/next/dist/compiled/webpack/bundle4.js:50928:4) {
  opensslErrorStack: [ 'error:030000[86](https://github.com/meshery/meshery/actions/runs/3835743870/jobs/6529301044#step:5:87):digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v***.12.1
Error: server closed unexpectedly
    at ChildProcess.onClose (/home/runner/work/meshery/meshery/ui/node_modules/start-server-and-test/src/index.js:75:14)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:10[91](https://github.com/meshery/meshery/actions/runs/3835743870/jobs/6529301044#step:5:92):16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
Error: Process completed with exit code 1.
```

#### Desired Behavior
cypress tests should not error out due to starting Meshery UI in development mode throwing a webpack 4 error coming from changes in internal open-ssl lib from Node ([webpack issue #14532](https://github.com/webpack/webpack/issues/14532)).

#### Implementation
According to [StackOverflow "Error message "error:0308010C:digital envelope routines::unsupported" question](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported) there are several ways to solve it but the wisest one is not to downgrade nor use legacy openssl flag because it leaves several security vulnerabilities unpatched and according to [reply "For me adding this in the script once is better than restricting the node version, the long term fix would be to migrate to webpack@5, I don't see additional value in sticking with node16"](https://github.com/webpack/webpack/issues/14532#issuecomment-1370851349) in [webpack issue #14532](https://github.com/webpack/webpack/issues/14532), long term fix is to migrate to webpack v5.

#### Acceptance Tests

???

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by acald-creator** [comment]
Closing issue for now.
