### ISSUE TITLE
[Performance] Nighthawk_service unavailable

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7823]
#### Current Behavior
Nighthawk cmd executer is not available, when running a test the server wants to run nighthawk_service  but it is not available, so no performance test could run. 

#### Screenshots/Logs
```
INFO[2023-06-08T21:10:26+05:30] perf test with config: &{istio_1686238735727  https://playground.meshery.io/ 15 10 <nil> <nil> []  false 30s nighthawk 0    true 0 false  false 0s}  app=meshery
ERRO[2023-06-08T21:10:26+05:30] stat /Users/abhi/code/meshery/meshery/server/cmd/nighthawk_service: no such file or directory  app=meshery code=2208 probable-cause="Load test endpoint could be not reachable" severity=2 short-description="load test error: .unable to perform" suggested-remediation="Make sure load test endpoint is reachable"
```

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Abhishek-kumar09** [comment]
From the discussion on the last call, we saw that infact the binary was available on the playground but is absent in case of local development.

**Comment by leecalcote** [comment]
Attempted fix: PR #7826

**Comment by leecalcote** [comment]
Here is the error received and crash that happens in the new Meshery edge release that uses :nighthawk: Nighthawk v0.7.0:
```
meshery-meshery-1        | []
meshery-meshery-1        | [Percentile:50  Value:0.074616831]
meshery-meshery-1        | [Percentile:50  Value:0.074616831 Percentile:75  Value:0.077443071]
meshery-meshery-1        | [Percentile:50  Value:0.074616831 Percentile:75  Value:0.077443071 Percentile:80  Value:0.077512703]
meshery-meshery-1        | [Percentile:50  Value:0.074616831 Percentile:75  Value:0.077443071 Percentile:80  Value:0.077512703 Percentile:90  Value:0.078753791]
meshery-meshery-1        | [Percentile:50  Value:0.074616831 Percentile:75  Value:0.077443071 Percentile:80  Value:0.077512703 Percentile:90  Value:0.078753791 Percentile:95  Value:0.087724031]
meshery-meshery-1        | [Percentile:50  Value:0.074616831 Percentile:75  Value:0.077443071 Percentile:80  Value:0.077512703 Percentile:90  Value:0.078753791 Percentile:95  Value:0.087724031]
meshery-meshery-1        | panic: invalid Go type string for field nighthawk.client.FortioResult.RequestedQPS
meshery-meshery-1        |
meshery-meshery-1        | goroutine 4133 [running]:
meshery-meshery-1        | google.golang.org/protobuf/internal/impl.newSingularConverter({0x4f04058?, 0x423b2a0}, {0x4f055a8, 0xc00075c1e0})
meshery-meshery-1        | 	/go/pkg/mod/google.golang.org/protobuf@v1.30.0/internal/impl/convert.go:142 +0xb1c
meshery-meshery-1        | google.golang.org/protobuf/internal/impl.NewConverter({0x4f04058, 0x423b2a0}, {0x4f055a8?, 0xc00075c1e0?})
meshery-meshery-1        | 	/go/pkg/mod/google.golang.org/protobuf@v1.30.0/internal/impl/convert.go:60 +0xa5
meshery-meshery-1        | google.golang.org/protobuf/internal/impl.fieldInfoForScalar({0x4f055a8, 0xc00075c1e0}, {{0x43eaf04, 0xc}, {0x0, 0x0}, {0x4f04058, 0x423b2a0}, {0x43eaf11, 0x4e}, ...}, ...)
meshery-meshery-1        | 	/go/pkg/mod/google.golang.org/protobuf@v1.30.0/internal/impl/message_reflect_field.go:270 +0x18a
meshery-meshery-1        | google.golang.org/protobuf/internal/impl.(*MessageInfo).makeKnownFieldsFunc(0xc0003af500, {0x8, {0x4f04058, 0x42364e0}, 0xffffffffffffffff, {0x0, 0x0}, 0x10, {0x4f04058, 0x41c26e0}, ...})
meshery-meshery-1        | 	/go/pkg/mod/google.golang.org/protobuf@v1.30.0/internal/impl/message_reflect.go:80 +0x7e8
meshery-meshery-1        | google.golang.org/protobuf/internal/impl.(*MessageInfo).makeReflectFuncs(0xc0003af500?, {0x4f04058, 0x4884fc0}, {0x8, {0x4f04058, 0x42364e0}, 0xffffffffffffffff, {0x0, 0x0}, 0x10, ...})
meshery-meshery-1        | 	/go/pkg/mod/google.golang.org/protobuf@v1.30.0/internal/impl/message_reflect.go:42 +0x65
meshery-meshery-1        | google.golang.org/protobuf/internal/impl.(*MessageInfo).initOnce(0xc0003af500)
meshery-meshery-1        | 	/go/pkg/mod/google.golang.org/protobuf@v1.30.0/internal/impl/message.go:90 +0x1d0
meshery-meshery-1        | google.golang.org/protobuf/internal/impl.(*MessageInfo).init(...)
meshery-meshery-1        | 	/go/pkg/mod/google.golang.org/protobuf@v1.30.0/internal/impl/message.go:72
meshery-meshery-1        | google.golang.org/protobuf/internal/impl.(*messageState).Range(0xc000e00b60?, 0xc00035ff50?)
meshery-meshery-1        | 	/go/pkg/mod/google.golang.org/protobuf@v1.30.0/internal/impl/message_reflect_gen.go:44 +0x45
meshery-meshery-1        | google.golang.org/protobuf/internal/order.RangeFields({0x7faca4108ac0, 0xc000e00b60}, 0x4af4c18, 0xc0078bf720)
meshery-meshery-1        | 	/go/pkg/mod/google.golang.org/protobuf@v1.30.0/internal/order/range.go:50 +0x15e
meshery-meshery-1        | google.golang.org/protobuf/encoding/protojson.encoder.marshalMessage({0xc0078bf6d0, {{}, 0x0, {0x0, 0x0}, 0x0, 0x0, 0x0, 0x0, {0x4edb548, ...}}}, ...)
meshery-meshery-1        | 	/go/pkg/mod/google.golang.org/protobuf@v1.30.0/encoding/protojson/encode.go:222 +0x334
meshery-meshery-1        | google.golang.org/protobuf/encoding/protojson.MarshalOptions.marshal({{}, 0x0, {0x0, 0x0}, 0x0, 0x0, 0x0, 0x0, {0x4edb548, 0xc000120e10}}, ...)
meshery-meshery-1        | 	/go/pkg/mod/google.golang.org/protobuf@v1.30.0/encoding/protojson/encode.go:135 +0x18e
meshery-meshery-1        | google.golang.org/protobuf/encoding/protojson.MarshalOptions.Marshal(...)
meshery-meshery-1        | 	/go/pkg/mod/google.golang.org/protobuf@v1.30.0/encoding/protojson/encode.go:109
meshery-meshery-1        | google.golang.org/protobuf/encoding/protojson.Marshal({0x4eac260?, 0xc000e00b60?})
meshery-meshery-1        | 	/go/pkg/mod/google.golang.org/protobuf@v1.30.0/encoding/protojson/encode.go:38 +0x67
meshery-meshery-1        | github.com/meshery/nighthawk-go/pkg/client.Transform(0xc0009f9220)
meshery-meshery-1        | 	/go/pkg/mod/github.com/meshery/nighthawk-go@v0.7.0/pkg/client/transform.go:66 +0xb54
meshery-meshery-1        | github.com/meshery/meshery/server/helpers.NighthawkLoadTest(0xc001bda240)
meshery-meshery-1        | 	/github.com/meshery/meshery/server/helpers/load_test_interface.go:410 +0x13a5
meshery-meshery-1        | github.com/meshery/meshery/server/handlers.(*Handler).executeLoadTest(0xc000914380, {0x4ed97c0?, 0xc00012e000}, 0xc0010da000, {0xc0002144a3, 0x24}, {0xc007748ab0, 0x15}, {0xc0002144f6, 0x0}, ...)
meshery-meshery-1        | 	/github.com/meshery/meshery/server/handlers/load_test_handler.go:346 +0x193
meshery-meshery-1        | github.com/meshery/meshery/server/handlers.(*Handler).loadTestHelperHandler.func2()
meshery-meshery-1        | 	/github.com/meshery/meshery/server/handlers/load_test_handler.go:320 +0xe5
meshery-meshery-1        | created by github.com/meshery/meshery/server/handlers.(*Handler).loadTestHelperHandler
meshery-meshery-1        | 	/github.com/meshery/meshery/server/handlers/load_test_handler.go:318 +0x712
meshery-meshery-1 exited with code 2
```

**Comment by MUzairS15** [comment]
Completed.
