### ISSUE TITLE
[Server] Adapters: Failed to build resolver

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7877]
#### Current Behavior
Meshery Server emits the following error log:

```
meshery-meshery-1        | time="2023-06-16T13:57:10Z" level=error msg="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp: lookup meshery-cilium on 127.0.0.11:53: no such host\"" app=meshery code=2041 probable-cause="unable to retrieve the requested data" severity=2 short-description="Error getting operations for the mesh.Error getting service mesh name" suggested-remediation="Make sure adapter is reachable and running"
meshery-meshery-1        | time="2023-06-16T13:57:10Z" level=error msg="fail to dial: failed to build resolver: passthrough: received empty target in Build()"
meshery-meshery-1        | 13:57:10 http: panic serving 172.19.0.1:43350: runtime error: invalid memory address or nil pointer dereference
meshery-meshery-1        | goroutine 4126 [running]:
meshery-meshery-1        | net/http.(*conn).serve.func1()
meshery-meshery-1        | 	/usr/local/go/src/net/http/server.go:1850 +0xbf
meshery-meshery-1        | panic({0x4413640, 0x695b0d0})
meshery-meshery-1        | 	/usr/local/go/src/runtime/panic.go:890 +0x262
meshery-meshery-1        | google.golang.org/grpc.(*ClientConn).Invoke(0x7f62f82f9a68?, {0x4ed5ab0?, 0xc000612960?}, {0x4999162?, 0x0?}, {0x458a4c0?, 0xc000c51c80?}, {0x466a1c0?, 0xc00115d090?}, {0x0, ...})
meshery-meshery-1        | 	/go/pkg/mod/google.golang.org/grpc@v1.54.0/call.go:32 +0x5e
meshery-meshery-1        | github.com/layer5io/meshery/server/meshes.(*meshServiceClient).SupportedOperations(0xc000a42410, {0x4ed5ab0, 0xc000612960}, 0x1?, {0x0, 0x0, 0x0})
meshery-meshery-1        | 	/github.com/meshery/meshery/server/meshes/meshops_grpc.pb.go:71 +0xce
meshery-meshery-1        | github.com/layer5io/meshery/server/handlers.(*Handler).addAdapter(0xc00085a3f0, {0x4ed5ab0, 0xc000612960}, {0x6d44980?, 0x0, 0x0}, 0xc0006129c0?, {0xc000082021, 0x1}, {0x4f0b538, ...})
meshery-meshery-1        | 	/github.com/meshery/meshery/server/handlers/mesh_ops_handlers.go:211 +0x2bc
meshery-meshery-1        | github.com/layer5io/meshery/server/handlers.(*Handler).SessionSyncHandler(0xc00085a3f0, {0x4ed2ed8?, 0xc000b49c00}, 0xc00268d300, 0xc0041cfc80, 0xc003c99080, {0x4f0b538, 0xc000c88000})
meshery-meshery-1        | 	/github.com/meshery/meshery/server/handlers/session_sync_handler.go:49 +0x7cc
meshery-meshery-1        | github.com/layer5io/meshery/server/handlers.(*Handler).MesheryControllersMiddleware.func1({0x4ed2ed8, 0xc000b49c00}, 0xc00268d300, 0x4e903e0?, 0x41aa640?, {0x4f0b538, 0xc000c88000})
meshery-meshery-1        | 	/github.com/meshery/meshery/server/handlers/middlewares.go:125 +0x308
meshery-meshery-1        | github.com/layer5io/meshery/server/handlers.(*Handler).KubernetesMiddleware.func1({0x4ed2ed8, 0xc000b49c00}, 0xc00417fc00, 0x4e90060?, 0x45e1da0?, {0x4f0b538, 0xc000c88000?})
meshery-meshery-1        | 	/github.com/meshery/meshery/server/handlers/middlewares.go:205 +0xb66
meshery-meshery-1        | github.com/layer5io/meshery/server/handlers.(*Handler).SessionInjectorMiddleware.func1({0x4ed2ed8, 0xc000b49c00}, 0xc00419ca00)
meshery-meshery-1        | 	/github.com/meshery/meshery/server/handlers/middlewares.go:258 +0x60b
meshery-meshery-1        | net/http.HandlerFunc.ServeHTTP(0xc0041b63c0?, {0x4ed2ed8?, 0xc000b49c00?}, 0xc0041b63c0?)
meshery-meshery-1        | 	/usr/local/go/src/net/http/server.go:2109 +0x2f
meshery-meshery-1        | github.com/layer5io/meshery/server/handlers.(*Handler).AuthMiddleware.func1({0x4ed2ed8?, 0xc000b49c00?}, 0xc00419ca00?)
meshery-meshery-1        | 	/github.com/meshery/meshery/server/handlers/middlewares.go:102 +0x282
meshery-meshery-1        | net/http.HandlerFunc.ServeHTTP(0x4ed5ab0?, {0x4ed2ed8?, 0xc000b49c00?}, 0x4e903d0?)
meshery-meshery-1        | 	/usr/local/go/src/net/http/server.go:2109 +0x2f
meshery-meshery-1        | github.com/layer5io/meshery/server/handlers.(*Handler).ProviderMiddleware.func1({0x4ed2ed8, 0xc000b49c00}, 0xc00419c900)
meshery-meshery-1        | 	/github.com/meshery/meshery/server/handlers/middlewares.go:54 +0x44d
meshery-meshery-1        | net/http.HandlerFunc.ServeHTTP(0xc00419c800?, {0x4ed2ed8?, 0xc000b49c00?}, 0xc0011549e0?)
meshery-meshery-1        | 	/usr/local/go/src/net/http/server.go:2109 +0x2f
meshery-meshery-1        | github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001cc780, {0x4ed2ed8, 0xc000b49c00}, 0xc00419c700)
meshery-meshery-1        | 	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
meshery-meshery-1        | net/http.serverHandler.ServeHTTP({0xc0041b61e0?}, {0x4ed2ed8, 0xc000b49c00}, 0xc00419c700)
meshery-meshery-1        | 	/usr/local/go/src/net/http/server.go:2947 +0x30c
meshery-meshery-1        | net/http.(*conn).serve(0xc003cfebe0, {0x4ed5ab0, 0xc00127dc50})
meshery-meshery-1        | 	/usr/local/go/src/net/http/server.go:1991 +0x607
meshery-meshery-1        | created by net/http.(*Server).Serve
meshery-meshery-1        | 	/usr/local/go/src/net/http/server.go:3102 +0x4db
```

#### Environment

- **Host OS:** Mac
- **Platform:** Docker
- **Meshery Server Version:** stable-v0.6.96

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@Revolyssup will you triage?
