### ISSUE TITLE
[Docs] GraphQL docs build error

### ISSUE THREAD

**Issue by abdullah1308** [meshery/meshery#7960]
#### Current State

After the change to Ruby v3.2.2 by #7933, I get the following error when trying to build the graphql docs -

```
abrafi@AbMacAir docs % bundle exec rake graphql:compile_docs --trace 
** Invoke graphql:compile_docs (first_time)
** Execute graphql:compile_docs
rake aborted!
NoMethodError: undefined method `to_hash' for "-# haml-lint:disable UnnecessaryStringOutput\n\n= auto_generated_comment\n\n:plain\n  Self-generated API documentation for Meshery's GraphQL API. The API can be explored interactively using the [GraphQL Playground](./extensibility). Documentation is generated from Meshery's GraphQL schema. Each table below documents a GraphQL type.\n\n  WARNING:\n  Fields that are deprecated are marked with **{warning-solid}**.\n\n  <!-- vale off -->\n\\\n\n:plain\n  ## `Query` type\n\n  The `Query` type contains the API's top-level entry points for all executable queries.\n\\\n\n- fields_of('Query').each do |field|\n  = render_full_field(field, heading_level: 3, owner: 'Query')\n  \\\n\n:plain\n  ## `Mutation` type\n\n  The `Mutation` type contains all the mutations you can execute.\n\n  All mutations receive their arguments in a single input object named `input`.\n\n\\\n\n- mutations.each do |field|\n  = render_full_field(field, heading_level: 3, owner: 'Mutation')\n  \\\n\n\n:plain\n  ## `Subscription` type\n\n  The `Subscription` type contains all the Subscriptions you can listen to.\n\n\n\\\n\n\n- subscriptions.each do |field|\n  = render_full_field(field, heading_level: 3, owner: 'Subscription')\n  \\\n\n:plain\n  ## Object types\n\n  Object types represent the resources that the Meshery GraphQL API can return.\n  They contain _fields_. Each field has its own type, which will either be one of the\n  basic GraphQL [scalar types](https://graphql.org/learn/schema/#scalar-types)\n  (e.g.: `String` or `Boolean`) or other object types. Fields may have arguments.\n  Fields with arguments are exactly like top-level queries, and are listed beneath\n  the table of fields for each object type.\n\n  For more information, see\n  [Object Types and Fields](https://graphql.org/learn/schema/#object-types-and-fields)\n  on `graphql.org`.\n\\\n\n- object_types.each do |type|\n  = render_name_and_description(type)\n  \\\n  = render_object_fields(type[:fields], owner: type)\n  \\\n\n:plain\n  ## Enumeration types\n\n  Also called _Enums_, enumeration types are a special kind of scalar that\n  is restricted to a particular set of allowed values.\n\n  For more information, see\n  [Enumeration Types](https://graphql.org/learn/schema/#enumeration-types)\n  on `graphql.org`.\n\\\n\n- enums.each do |enum|\n  = render_name_and_description(enum)\n  \\\n  ~ \"| Value | Description |\"\n  ~ \"| ----- | ----------- |\"\n  - enum[:values].each do |value|\n    = render_enum_value(enum, value)\n  \\\n\n:plain\n  ## Scalar types\n\n  Scalar values are atomic values, and do not have fields of their own.\n  Basic scalars include strings, boolean values, and numbers. This schema also\n  defines various custom scalar values, such as types for times and dates.\n\n  This schema includes custom scalar types for identifiers, with a specific type for\n  each kind of object.\n\n  For more information, read about [Scalar Types](https://graphql.org/learn/schema/#scalar-types) on `graphql.org`.\n\\\n\n- graphql_scalar_types.each do |type|\n  = render_name_and_description(type)\n  \\\n\n  -# Current GraphQL is not using Abstract Types. Can be uncommented for future use.\n\n  -# :plain\n  -#   ## Abstract types\n\n  -#   Abstract types (unions and interfaces) are ways the schema can represent\n  -#   values that may be one of several concrete types.\n\n  -#   - A [`Union`](https://graphql.org/learn/schema/#union-types) is a set of possible types.\n  -#     The types might not have any fields in common.\n  -#   - An [`Interface`](https://graphql.org/learn/schema/#interfaces) is a defined set of fields.\n  -#     Types may `implement` an interface, which\n  -#     guarantees that they have all the fields in the set. A type may implement more than\n  -#     one interface.\n\n  -#   See the [GraphQL documentation](https://graphql.org/learn/) for more information on using\n  -#   abstract types.\n  -# \\\n\n  -# :plain\n  -#   ### Unions\n  -# \\\n\n  -# - graphql_union_types.each do |type|\n  -#   = render_name_and_description(type, level: 4)\n  -#   \\\n  -#   One of:\n  -#   \\\n  -#   - type[:possible_types].each do |member|\n  -#     = render_union_member(member)\n  -#   \\\n\n  -# :plain\n  -#   ### Interfaces\n  -# \\\n\n  -# - interfaces.each do |type|\n  -#   = render_name_and_description(type, level: 4)\n  -#   \\\n  -#   Implementations:\n  -#   \\\n  -#   - type[:implemented_by].each do |type_name|\n  -#     ~ \"- [`\#{type_name}`](#\#{type_name.downcase})\"\n  -#   \\\n  -#   = render_object_fields(type[:fields], owner: type, level_bump: 1)\n  -#   \\\n\n:plain\n  ## Input types\n\n  Types that may be used as arguments (all scalar types may also\n  be used as arguments).\n\n  Only general use input types are listed here. For mutation input types,\n  see the associated mutation type above.\n\n  For more information, read about [Scalar Types](https://graphql.org/learn/schema/#input-types) on `graphql.org`.\n\n\\\n\n- input_types.each do |type|\n  = render_name_and_description(type)\n  \\\n  = render_argument_table(3, type[:input_fields], type[:name])\n  \\\n":String
/opt/homebrew/lib/ruby/gems/3.2.0/gems/temple-0.10.2/lib/temple/map.rb:88:in `validate_map!'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/temple-0.10.2/lib/temple/mixins/options.rb:82:in `initialize'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/temple-0.10.2/lib/temple/engine.rb:46:in `initialize'
/Users/abrafi/Code/OpenSource/layer5/meshery/meshery/docs/lib/tasks/renderer.rb:23:in `new'
/Users/abrafi/Code/OpenSource/layer5/meshery/meshery/docs/lib/tasks/renderer.rb:23:in `initialize'
/Users/abrafi/Code/OpenSource/layer5/meshery/meshery/docs/Rakefile:24:in `new'
/Users/abrafi/Code/OpenSource/layer5/meshery/meshery/docs/Rakefile:24:in `block (2 levels) in <top (required)>'
/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/opt/homebrew/Cellar/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/opt/homebrew/opt/ruby/bin/rake:25:in `load'
/opt/homebrew/opt/ruby/bin/rake:25:in `<main>'
Tasks: TOP => graphql:compile_docs
```
I'm running the following ruby version - 

```
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin21]
```

Previously I was able to build the docs with Ruby v2.7.5

I suspect the change in the ruby version is causing this workflow to fail as well -

https://github.com/meshery/meshery/actions/runs/5366494012/jobs/9757454671

#### Desired State

GraphQL docs should be succesfully built on running `bundle exec rake graphql:compile_docs`

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by yash37158** [comment]
I would like to work on this issue @abdullah1308 @leecalcote
